import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService {
  static final LocalizationService instance = LocalizationService._internal();
  LocalizationService._internal();

  static const String _prefKey = 'selected_language';
  final ValueNotifier<String> currentLocale = ValueNotifier<String>('en');

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    final savedLang = prefs.getString(_prefKey) ?? 'en';
    currentLocale.value = savedLang;
  }

  Future<void> setLocale(String langCode) async {
    currentLocale.value = langCode;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefKey, langCode);
  }

  void toggleLanguage() {
    if (currentLocale.value == 'en') {
      setLocale('ur');
    } else {
      setLocale('en');
    }
  }

  bool get isUrdu => currentLocale.value == 'ur';

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'Parwarish.ai',
      'tagline': 'Empowering extraordinary minds with love & play',
      'welcome_back': 'Welcome Back!',
      'parent_login': 'Parent Portal',
      'child_login': 'Child Space',
      'therapist_login': 'Therapist Portal',
      'email': 'Email Address',
      'password': 'Password',
      'sign_in': 'Sign In',
      'sign_in_with_google': 'Continue with Google',
      'sign_in_with_apple': 'Continue with Apple',
      'demo_login': 'Explore Demo Mode',
      'quick_access': 'Quick Child Access',
      'select_profile': 'Choose Your Hero Profile',
      'add_child': 'Add Child Profile',
      'child_name': 'Child Name',
      'save_child': 'Save Profile',
      'parent_dashboard': 'Parent Dashboard',
      'analytics_title': 'Growth & Strengths',
      'child_profiles': 'My Little Champions',
      'total_play_time': 'Total Active Learning Time',
      'modules_completed': 'Missions Completed',
      'current_streak': 'Day Streak',
      'days': 'Days',
      'mins': 'Mins',
      'daily_reports': 'Daily Reports from Therapist',
      'daily_strengths': 'Daily Strengths & Joys',
      'view_daily_report': 'View Detailed Therapist Report',
      'therapist_notes': 'Therapist Clinical Insights',
      'home_tip': 'Recommended Fun Home Activity',
      'tab_learn': 'Play & Learn',
      'tab_schedule': 'My Routine',
      'tab_badges': 'My Badges',
      'pet_greeting': 'Hello superstar! Let’s play today’s fun mission!',
      'pet_happy_praise': 'You did it! You are a brilliant superstar!',
      'tap_to_talk': 'Tap to talk to your companion',
      'start_lesson': 'Start Mission',
      'how_did_you_feel': 'How did you feel during this mission?',
      'mood_happy': 'Happy & Joyful 😄',
      'mood_calm': 'Calm & Peaceful 🧘',
      'mood_excited': 'Super Excited ⚡',
      'mood_focused': 'Super Focused 🎯',
      'mood_tired': 'A bit tired 😴',
      'congratulations': 'Awesome Job!',
      'reward_stars': '+50 Stars Earned!',
      'continue_btn': 'Continue Adventure',
      'logout': 'Sign Out',
      'switch_role': 'Switch Account Role',
      'no_children_yet': 'No child profiles yet. Tap + to create one!',
      'no_reports_yet': 'No therapist reports yet. Check back after today’s session!',
      'therapist_dashboard': 'Therapist Clinical Portal',
      'tab_manage_kids': 'Enrolled Children',
      'tab_domains': '22 Clinical Domains',
      'tab_datasheet': 'Clinical Datasheet',
      'tab_schedule_builder': 'Schedule Builder',
      'tab_report_dispatch': 'Send Daily Report',
      'clinical_level': 'Clinical Support Level',
      'assign_goal': 'Assign to Schedule',
      'scheduled_for': 'Scheduled for: ',
      'datasheet_title': 'Clinical Datasheet & Record Manager',
      'datasheet_subtitle': 'Multi-child session telemetry, prompt hierarchies, mastery tracking & clinical notes',
      'new_session_entry': 'Log Session Entry',
      'clinical_profile': 'Case Profile',
      'export_data': 'Export Datasheet',
      'search_records': 'Search notes, goals or keywords...',
      'filter_domain': 'All Domains',
      'filter_session_type': 'All Session Types',
      'table_date': 'Date & Type',
      'table_domain_goal': 'Domain & Clinical Goal',
      'table_prompt': 'Prompt Level',
      'table_trials': 'Trials / Mastery',
      'table_sensory': 'Sensory State',
      'table_notes': 'Clinical Notes',
      'table_actions': 'Actions',
      'prompt_independent': 'Independent',
      'prompt_gestural': 'Gestural Prompt',
      'prompt_verbal': 'Verbal Prompt',
      'prompt_modeling': 'Modeling Prompt',
      'prompt_partial_physical': 'Partial Physical',
      'prompt_full_physical': 'Full Physical',
      'session_aba': 'ABA Therapy',
      'session_speech': 'Speech & Language',
      'session_ot': 'Occupational Therapy',
      'session_social': 'Social Skills Group',
      'session_baseline': 'Baseline Assessment',
      'sensory_regulated': 'Regulated & Calm',
      'sensory_hypersensitive': 'Hypersensitive',
      'sensory_hyposensitive': 'Hyposensitive',
      'sensory_seeking': 'Sensory Seeking',
      'sensory_fatigued': 'Fatigued / Low Energy',
      'trials_count': 'Trials Attempted',
      'successful_trials': 'Successful Trials',
      'mastery_rate': 'Mastery Rate',
      'behavioral_notes': 'Behavioral Observations (ABC)',
      'clinical_notes_hint': 'Detailed clinical impressions, prompting nuances...',
      'home_recommendations': 'Home / Parent Recommendations',
      'next_session_targets': 'Next Session Targets',
      'save_entry': 'Save Session Entry',
      'delete_entry': 'Delete Entry',
      'delete_confirm': 'Are you sure you want to delete this datasheet entry?',
      'csv_exported': 'Datasheet CSV generated successfully!',
      'copy_csv': 'Copy CSV to Clipboard',
      'copy_summary': 'Copy Case Summary',
    },
    'ur': {
      'app_name': 'پرورش ڈاٹ اے آئی',
      'tagline': 'محبت، کھیل اور سائنسی مہارت سے بچوں کی بہترین رہنمائی',
      'welcome_back': 'خوش آمدید!',
      'parent_login': 'والدین کا پورٹل',
      'child_login': 'بچوں کا کارنر',
      'therapist_login': 'ماہرِ امراض (تھراپسٹ)',
      'email': 'ای میل ایڈریس',
      'password': 'پاس ورڈ',
      'sign_in': 'لاگ ان کریں',
      'sign_in_with_google': 'گوگل کے ساتھ لاگ ان',
      'sign_in_with_apple': 'ایپل کے ساتھ لاگ ان',
      'demo_login': 'ڈیمو موڈ دیکھیں',
      'quick_access': 'بچوں کا فوری داخلہ',
      'select_profile': 'اپنا پروفائل منتخب کریں',
      'add_child': 'نیا پروفائل شامل کریں',
      'child_name': 'بچے کا نام',
      'save_child': 'پروفائل محفوظ کریں',
      'parent_dashboard': 'والدین کا ڈیش بورڈ',
      'analytics_title': 'ترقی اور نمایاں صلاحیتیں',
      'child_profiles': 'ہمارے پیارے چیمپیئنز',
      'total_play_time': 'سیکھنے کا کل وقت',
      'modules_completed': 'مکمل شدہ مشنز',
      'current_streak': 'مسلسل دن (Streak)',
      'days': 'دن',
      'mins': 'منٹ',
      'daily_reports': 'تھراپسٹ کی روزانہ کی رپورٹ',
      'daily_strengths': 'روزانہ کی خوبیاں اور ادراک',
      'view_daily_report': 'تھراپسٹ کی تفصیلی رپورٹ دیکھیں',
      'therapist_notes': 'ماہر تھراپسٹ کے تاثرات',
      'home_tip': 'گھر میں کرنے کی خوشگوار مشق',
      'tab_learn': 'سیکھیں اور کھیلیں',
      'tab_schedule': 'میرا شیڈول',
      'tab_badges': 'میرے انعامات',
      'pet_greeting': 'ہیلو سپر اسٹار! آئیں آج کا مزے دار مشن کریں!',
      'pet_happy_praise': 'شاباش! آپ نے بہت شاندار کارکردگی دکھائی!',
      'tap_to_talk': 'بات کرنے کے لیے دوست کو چھوئیں',
      'start_lesson': 'مشن شروع کریں',
      'how_did_you_feel': 'اس مشن کے دوران آپ نے کیسا محسوس کیا؟',
      'mood_happy': 'بہت خوش اور پرجوش 😄',
      'mood_calm': 'پرسکون اور آرام دہ 🧘',
      'mood_excited': 'بہت انرجیٹک ⚡',
      'mood_focused': 'مکمل توجہ کے ساتھ 🎯',
      'mood_tired': 'تھوڑا سا تھکا ہوا 😴',
      'congratulations': 'شاندار کارکردگی!',
      'reward_stars': '+۵۰ ستارے ملے!',
      'continue_btn': 'جاری رکھیں',
      'logout': 'لاگ آؤٹ',
      'switch_role': 'اکاؤنٹ کا کردار تبدیل کریں',
      'no_children_yet': 'ابھی کوئی پروفائل موجود نہیں۔ نیا شامل کرنے کے لیے + دبائیں!',
      'no_reports_yet': 'ابھی کوئی رپورٹ موصول نہیں ہوئی۔ آج کی سرگرمی کے بعد حاضر ہوگی!',
      'therapist_dashboard': 'تھراپسٹ کلینیکل پورٹل',
      'tab_manage_kids': 'زیرِ تربیت بچے',
      'tab_domains': '۲۲ کلینیکل شعبے',
      'tab_datasheet': 'کلینیکل ڈیٹا شیٹ',
      'tab_schedule_builder': 'شیڈول ترتیب دیں',
      'tab_report_dispatch': 'رپورٹ ارسال کریں',
      'clinical_level': 'کلینیکل سپورٹ کا درجہ',
      'assign_goal': 'شیڈول میں شامل کریں',
      'scheduled_for': 'وقت مقررہ: ',
      'datasheet_title': 'کلینیکل ڈیٹا شیٹ و کیس ریکارڈز',
      'datasheet_subtitle': 'سیشن کے اندراجات، پرامپٹ کی سطح، کامیابی کی شرح اور کلینیکل نوٹس',
      'new_session_entry': 'نیا سیشن اندراج',
      'clinical_profile': 'کیس پروفائل',
      'export_data': 'ڈیٹا شیٹ ایکسپورٹ',
      'search_records': 'نوٹس، اہداف یا مطلوبہ الفاظ تلاش کریں...',
      'filter_domain': 'تمام شعبے',
      'filter_session_type': 'تمام سیشن اقسام',
      'table_date': 'تاریخ و نوعیت',
      'table_domain_goal': 'شعبہ و کلینیکل ہدف',
      'table_prompt': 'پرامپٹ کی سطح',
      'table_trials': 'ٹرائلز / کامیابی',
      'table_sensory': 'حسی حالت (Sensory)',
      'table_notes': 'کلینیکل نوٹس',
      'table_actions': 'اقدامات',
      'prompt_independent': 'خود مختار (Independent)',
      'prompt_gestural': 'اشاروں کی مدد (Gestural)',
      'prompt_verbal': 'زبانی رہنمائی (Verbal)',
      'prompt_modeling': 'دیکھ کر سیکھنا (Modeling)',
      'prompt_partial_physical': 'ہلکی جسمانی مدد (Partial Physical)',
      'prompt_full_physical': 'مکمل جسمانی مدد (Full Physical)',
      'session_aba': 'اے بی اے تھراپی (ABA)',
      'session_speech': 'اسپیچ و لینگویج تھراپی',
      'session_ot': 'اوکیوپیشنل تھراپی (OT)',
      'session_social': 'سوشل اسکلز گروپ',
      'session_baseline': 'بیس لائن تشخیصی سیشن',
      'sensory_regulated': 'متوازن و پرسکون',
      'sensory_hypersensitive': 'حساسیت زیادہ (Hypersensitive)',
      'sensory_hyposensitive': 'حساسیت کم (Hyposensitive)',
      'sensory_seeking': 'حسی تسکین کا متلاشی',
      'sensory_fatigued': 'تھکا ہوا / کم توانائی',
      'trials_count': 'کل ٹرائلز',
      'successful_trials': 'کامیاب ٹرائلز',
      'mastery_rate': 'کامیابی کی شرح',
      'behavioral_notes': 'رویہ کے مشاہدات (ABC)',
      'clinical_notes_hint': 'کلینیکل مشاہدات اور اہم نکات درج کریں...',
      'home_recommendations': 'گھر کے لیے تجاویز',
      'next_session_targets': 'اگلے سیشن کے اہداف',
      'save_entry': 'اندراج محفوظ کریں',
      'delete_entry': 'اندراج حذف کریں',
      'delete_confirm': 'کیا آپ واقعی اس سیشن کے اندراج کو حذف کرنا چاہتے ہیں؟',
      'csv_exported': 'ڈیٹا شیٹ CSV تیار ہو گئی ہے!',
      'copy_csv': 'CSV کاپی کریں',
      'copy_summary': 'کیس سمری کاپی کریں',
    },
  };

  String tr(String key) {
    final lang = currentLocale.value;
    return _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
